import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class TermsConditons extends StatelessWidget {
  const TermsConditons({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        iconTheme: IconThemeData(color: Color(0xffffFFFFFF)),
        backgroundColor: Color(0xff00C6D8),
        title: Text("TERMS & CONDITIONS",
            style: GoogleFonts.quicksand(
              textStyle: const TextStyle(
                  color: Color(0xffffFFFFFF),
                  fontWeight: FontWeight.w500,
                  fontSize: 19),
            )),
        actions: [
          IconButton(
              onPressed: () {},
              icon: Icon(
                Icons.person_pin,
                color: Color(0xffffFFFFFF),
              ))
        ],
      ),


      body: Container(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                child: Text("Welcome to our Website. These terms and conditions apply to the access and use of the Website https://www.trustmoney.com and its Mobile Application (collectively be referred to as Platform), which is managed and operated by Techwealth Capital Services Private Limited, a company incorporated under the Companies Act, 2013 having its Registered Office at 3rd Floor, Sheraton House, opposite Ketav Petrol Pump, Polytechnic road, Ambawadi, Ahmedabad 380015 (hereinafter referred to as the Company). The Company is in the business of enabling users to make investments in financial instruments as offered by the Company on the platform either (i) by acting as an intermediary through financial institutions and the users; or (ii) by enabling the user to make an investment in a financial instrument directly with the Company. (Here in after referred to as our “Services”). The Company can be contacted through mail at connect@tipsons.com We have entered in to Technology Service Agreement with Tipsons Financial Services Private Limited, a company incorporated under the Companies Act 1956 having its Registered Office at 401, Sheraton House, opposite Ketav Petrol Pump, Polytechnic road, Ambawadi, Ahmedabad 380015 for outsourcing this platform for providing the financial services and solutions to their clients. Hence all this terms and conditions enumerated below will be applicable to all those accessing and using this platform. This document is an electronic record in terms of Information Technology Act, 2000 and generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 of the Information Technology (Intermediaries guidelines) 2011, that provides for the due diligence to be exercised for the access or usage of Platform.",style:  GoogleFonts.sourceSansPro(
                  textStyle: const TextStyle(
                    color: Color(0xff22263D), fontWeight: FontWeight.w400, fontSize: 16,),
                ),),
              ),
              SizedBox(height: 20,),

              Container(
                child: Text(
                  "Acceptance Of Terms And Conditions",style:  GoogleFonts.quicksand(
                    textStyle: const TextStyle(
                        color: Color(0xff22263D), fontSize: 20, fontWeight: FontWeight.bold))
                  ,
                ),
              ),

              SizedBox(height: 10,),
              Container(
                child: Text("1. DEFINITIONS",style: GoogleFonts.quicksand(
                    textStyle: const TextStyle(
                        color: Color(0xff22263D), fontSize: 20, fontWeight: FontWeight.bold)),),
              ),

              Container(
                child: Text(
                  "The below enumerated terms shall have the following meanings:  a. “Applicable Law(s)” means any laws, statutes, rules, regulations, orders, circulars, decrees, directives, judgments, decisions or other similar mandates of central, state or local governmental authority having competent jurisdiction in the territory of India; or laws application to the Party or subject matter in question. b. “Document” shall mean and include the “Terms of Use including Disclaimer and Disclosure statement,” “Privacy Policy”, as provided on this Platform. c. Intellectual Property” / “Intellectual Property Rights” means all current and future copyright, patents, trademarks (whether or not registered) or any other rights in databases, computer program, source code, process inventions or trade secrets, know-how, rights in designs, topographies, trade and business names, domain names, logo and all other intellectual and property rights and applications for any of those rights (where such applications can be made) capable of protection under the Applicable Laws for the time being in force. d. “Services” shall mean Services of every description as available on the Platform for Users (including potential users). e. “Users” shall mean the person(s) accessing/ visiting/ using this Platform. f. “Vendor” shall mean the entities empanelled with the Company to display their products/ offerings and educative initiatives etc. on this Platform. g. “Terms of Use” shall mean the terms and conditions set out herein regarding the use of the Platform.",style:  GoogleFonts.sourceSansPro(
                    textStyle: const TextStyle(
                      color: Color(0xff22263D), fontWeight: FontWeight.w400, fontSize: 16,),)
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
